# Generated by Django 4.2.25 on 2025-10-29 04:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_alter_comment_id_alter_post_id_follower'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follower',
            old_name='follower',
            new_name='follows',
        ),
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together={('user', 'follows')},
        ),
    ]
